from langchain.prompts import PromptTemplate

# Prompt
prompt_template = PromptTemplate(
    template="""You are an investment analyst. You will be given: 
    <INSTRUCTIONS>
    You will be provided:
    1. a QUESTION asked by the user
    2. DOCUMENTS provided by an automated context retrieval system
    
    Your task is to use the context to provide a relevant ANSWER to the QUESTION

    Only answer what the user is asking and nothing else
    
    Explain your reasoning in a step-by-step manner. Ensure your reasoning and conclusion are correct. 

    Avoid simply stating the correct answer at the outset.

    If there is no relevant context provided, state that at the outset.

    At the end of your calculations create a section for the final answer submission. Example:
    <ANSWER>
    29.31%
    </ANSWER>
    </INSTRUCTIONS>
    <QUESTION>{question}</QUESTION>\n
    <DOCUMENTS>
    \n\n {documents}
    </DOCUMENTS>\n\n
    <QUESTION>{question}</QUESTION>\n
    """,
    input_variables=["question", "documents"],
)

# Prompt
eval_prompt_template = PromptTemplate(
    template="""You are an evaluator for an algorithm that answers investment analyst questions.

    You will be provided:
    1. QUESTION: question asked by the user
    2. ACTUAL_ANSWER: answer generated by the algorithm
    3. EXPECTED_ANSWER: expected answer

    Your task is to evaluate the algorithm's provided answer based on how well it matches the expected answer.
    
    Only provide a number between 0 and 1 for your evaluation and nothing else. DO NOT provide explanations.

    0 is the lowest score (completely wrong) and 1 is the highest score (perfect answer).

    <QUESTION>{question}</QUESTION>\n
    <ACTUAL_ANSWER>{actual_answer}</ACTUAL_ANSWER>\n
    <EXPECTED_ANSWER>{expected_answer}</EXPECTED_ANSWER>\n

    Example:
    <QUESTION>What is the percentage change in the net cash from operating activities from 2008 to 2009?</QUESTION>
    <ACTUAL_ANSWER>29.31</ACTUAL_ANSWER>
    <EXPECTED_ANSWER>29.31%</EXPECTED_ANSWER>

    Output:
    1.0
    """,
    input_variables=["question", "actual_answer", "expected_answer"],
)
